package com.da.sanon;
import android.app.*;import android.app.WallpaperManager;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{
  GridLayout grid; int selected=0;
  public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xff101014);
    TextView head=new TextView(this);head.setText("SANON   •   360 רקעים אופליין");head.setTextColor(Color.WHITE);head.setTextSize(21);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(18,8,8,8);root.addView(head,new LinearLayout.LayoutParams(-1,64));
    HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout cats=new LinearLayout(this);String[] a={"הכול","טבע","חלל","עיר","רכב","טכנולוגיה","אבסטרקט","כהה","צבעוני","מינימליסטי"};
    for(String s:a){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setGravity(17);t.setPadding(18,4,18,4);GradientDrawable g=new GradientDrawable();g.setColor(0xff303038);g.setCornerRadius(40);t.setBackground(g);cats.addView(t,new LinearLayout.LayoutParams(-2,48));t.setOnClickListener(v->filter(s));}hs.addView(cats);root.addView(hs);
    ScrollView sv=new ScrollView(this);grid=new GridLayout(this);grid.setColumnCount(3);sv.addView(grid);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);filter("הכול");}
  void filter(String s){grid.removeAllViews();String[] names={"הכול","טבע","חלל","עיר","רכב","טכנולוגיה","אבסטרקט","כהה","צבעוני","מינימליסטי"};int f=-1;for(int j=1;j<names.length;j++)if(names[j].equals(s))f=j-1;for(int i=0;i<360;i++){if(f>=0&&i%9!=f)continue;final int id=i;View v=new View(this){protected void onDraw(Canvas c){WallpaperArt.draw(c,getWidth(),getHeight(),id);}};v.setOnClickListener(x->preview(id));GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=250;p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(5,5,5,5);grid.addView(v,p);}}
  void preview(int id){Dialog d=new Dialog(this);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);View v=new View(this){protected void onDraw(Canvas c){WallpaperArt.draw(c,getWidth(),getHeight(),id);}};l.addView(v,new LinearLayout.LayoutParams(-1,0,1));Button b=new Button(this);b.setText("הגדר כרקע");b.setOnClickListener(x->{setWallpaper(id);d.dismiss();});l.addView(b,new LinearLayout.LayoutParams(-1,60));d.setContentView(l);d.show();Window w=d.getWindow();if(w!=null)w.setLayout(-1,-1);}
  void setWallpaper(int id){try{Bitmap b=Bitmap.createBitmap(1080,1920,Bitmap.Config.ARGB_8888);WallpaperArt.draw(new Canvas(b),1080,1920,id);WallpaperManager.getInstance(this).setBitmap(b);Toast.makeText(this,"הרקע הוגדר",0).show();}catch(Exception e){Toast.makeText(this,"שגיאה בהגדרת הרקע",0).show();}}
}