package com.da.info;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout content; TextView status; JSONArray cats; final int BG=Color.rgb(8,12,22),CARD=Color.rgb(18,24,38),WHITE=Color.WHITE,MUTED=Color.rgb(155,166,188),ACC=Color.rgb(124,156,255);
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);content=findViewById(R.id.content);status=findViewById(R.id.status);load();home();}
 void load(){try{InputStream in=getAssets().open("data.json");byte[] x=new byte[in.available()];in.read(x);cats=new JSONObject(new String(x,StandardCharsets.UTF_8)).getJSONArray("categories");}catch(Exception e){cats=new JSONArray();}}
 TextView txt(String s,float z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.RIGHT);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);v.setPadding(4,6,4,6);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;} void clear(){content.removeAllViews();}
 void home(){clear();content.addView(txt("DA מידע",30,WHITE,true));content.addView(txt("אנציקלופדיה אישית — אופליין",16,ACC,true));content.addView(txt("ידע קצר, ברור ונגיש במגוון תחומים",14,MUTED,false));EditText q=new EditText(this);q.setHint("חיפוש במאגר…");q.setTextColor(WHITE);q.setHintTextColor(MUTED);q.setGravity(Gravity.RIGHT);content.addView(q);Button s=btn("🔎 חיפוש");s.setOnClickListener(v->search(q.getText().toString()));content.addView(s);for(int i=0;i<cats.length();i++){try{JSONObject c=cats.getJSONObject(i);card(c);}catch(Exception ignored){}}status.setText("אופליין • "+count()+" ערכים מקומיים • ללא צורך באינטרנט");}
 int count(){int n=0;for(int i=0;i<cats.length();i++)try{n+=cats.getJSONObject(i).getJSONArray("items").length();}catch(Exception ignored){}return n;}
 void card(JSONObject c){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(14,12,14,12);box.setBackgroundColor(CARD);box.addView(txt(c.optString("title"),19,WHITE,true));box.addView(txt(c.optJSONArray("items").length()+" ערכים",13,ACC,false));Button b=btn("פתח קטגוריה");b.setOnClickListener(v->category(c));box.addView(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,10);content.addView(box,p);}
 void category(JSONObject c){clear();Button back=btn("← חזרה");back.setOnClickListener(v->home());content.addView(back);content.addView(txt(c.optString("title"),26,WHITE,true));JSONArray a=c.optJSONArray("items");for(int i=0;i<a.length();i++)try{JSONObject it=a.getJSONObject(i);article(it);}catch(Exception ignored){}status.setText(c.optString("title")+" • אופליין");}
 void article(JSONObject it){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(14,10,14,10);box.setBackgroundColor(CARD);box.addView(txt(it.optString("title"),18,WHITE,true));box.addView(txt(it.optString("body"),14,MUTED,false));content.addView(box,new LinearLayout.LayoutParams(-1,-2));}
 void search(String q){clear();Button back=btn("← חזרה");back.setOnClickListener(v->home());content.addView(back);content.addView(txt("תוצאות חיפוש",25,WHITE,true));String z=q==null?q.trim().toLowerCase():"";int hits=0;for(int i=0;i<cats.length();i++)try{JSONObject c=cats.getJSONObject(i);JSONArray a=c.getJSONArray("items");for(int j=0;j<a.length();j++){JSONObject it=a.getJSONObject(j);String hay=(it.optString("title")+" "+it.optString("body")+" "+c.optString("title")).toLowerCase();if(z.isEmpty()||hay.contains(z)){article(it);hits++;}}}catch(Exception ignored){}if(hits==0)content.addView(txt("לא נמצאו ערכים מתאימים.",16,MUTED,false));status.setText("חיפוש אופליין • "+hits+" תוצאות");}
}