package com.da.osiris;
import android.app.Activity;import android.graphics.Color;import android.graphics.Typeface;import android.os.Bundle;import android.view.Gravity;import android.widget.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 private OfflineStore store;private LinearLayout content;private TextView status;private final Map<String,String> sections=new LinkedHashMap<>();private final int WHITE=Color.WHITE,MUTED=Color.rgb(160,171,184),BLUE=Color.rgb(105,199,255),CARD=Color.rgb(20,27,35);
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);store=new OfflineStore(this);content=findViewById(R.id.content);status=findViewById(R.id.status);init();home();}
 private void init(){String[][]a={{"✈️ טיסות","flights"},{"🛰️ לוויינים","satellites"},{"🌍 רעידות אדמה","earthquakes"},{"🔥 שריפות","fires"},{"🌦️ מזג אוויר","weather"},{"🌫️ איכות אוויר","airQuality"},{"📡 מכ״ם / GPS","radar"},{"☀️ מזג חלל","spaceWeather"},{"🌐 אירועים גאופוליטיים","conflicts"},{"🚢 ימאות","maritime"},{"🛡️ איומי סייבר","cyberThreats"},{"📈 שווקים","markets"},{"₿ קריפטו","crypto"},{"📹 מצלמות ציבוריות","cctv"}};for(String[]x:a)sections.put(x[0],x[1]);}
 private TextView t(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.RIGHT);v.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);v.setPadding(0,6,0,6);return v;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;} private void clear(){content.removeAllViews();}
 private void home(){clear();content.addView(t("DA OSIRIS",30,WHITE,true));content.addView(t("מרכז מידע מודיעיני אופליין",17,BLUE,true));content.addView(t("Snapshot: "+store.capturedAt(),13,MUTED,false));content.addView(t("סה״כ פריטים מקומיים: "+store.total(),15,WHITE,true));if(store.isTestData())content.addView(t("⚠ נתוני seed — Build של GitHub יחליף אותם ב-Snapshot אמיתי.",14,Color.rgb(255,190,100),true));EditText q=new EditText(this);q.setHint("חיפוש בכל המאגר…");q.setTextColor(WHITE);q.setHintTextColor(MUTED);q.setGravity(Gravity.RIGHT);content.addView(q);Button sb=btn("🔎 חפש");sb.setOnClickListener(v->search(q.getText().toString()));content.addView(sb);for(Map.Entry<String,String>e:sections.entrySet())card(e.getKey(),e.getValue());status.setText("אופליין • ללא הרשאת אינטרנט • "+store.total()+" פריטים");}
 private void card(String label,String k){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(16,12,16,12);box.setBackgroundColor(CARD);box.addView(t(label,18,WHITE,true));box.addView(t(store.endpoint(k),12,MUTED,false));box.addView(t("פריטים: "+store.count(k),13,BLUE,false));Button b=btn("פתח");b.setOnClickListener(v->section(k,label));box.addView(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,10);content.addView(box,p);}
 private void section(String k,String label){clear();Button back=btn("← חזרה");back.setOnClickListener(v->home());content.addView(back);content.addView(t(label,25,WHITE,true));content.addView(t("Endpoint: "+store.endpoint(k),13,MUTED,false));render(store.data(k),0);status.setText(label+" • אופליין");}
 private void render(Object v,int d){if(d>3)return;if(v instanceof JSONArray){JSONArray a=(JSONArray)v;for(int i=0;i<a.length();i++){content.addView(t("פריט "+(i+1),16,BLUE,true));render(a.opt(i),d+1);}}else if(v instanceof JSONObject){JSONObject o=(JSONObject)v;Iterator<String>i=o.keys();while(i.hasNext()){String k=i.next();Object x=o.opt(k);if(x instanceof JSONObject||x instanceof JSONArray){content.addView(t("▸ "+k,15,WHITE,true));render(x,d+1);}else content.addView(t(k+": "+String.valueOf(x),13,MUTED,false));}}else if(v!=null)content.addView(t(String.valueOf(v),13,MUTED,false));}
 private void search(String q){clear();Button back=btn("← חזרה");back.setOnClickListener(v->home());content.addView(back);content.addView(t("תוצאות חיפוש",25,WHITE,true));try{JSONArray a=new JSONArray(store.search(q));content.addView(t("קטגוריות שנמצאו: "+a.length(),15,BLUE,true));for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);content.addView(t("• "+x.optString("section"),18,WHITE,true));render(x.opt("data"),0);}}catch(Exception e){content.addView(t("שגיאה בחיפוש",16,Color.RED,true));}status.setText("חיפוש אופליין");}
}